### ISSUE TITLE
Nature Renderer doesn't recognize terrain

### ISSUE THREAD

**Issue by NoelWidmer** [visualdesigncafe/nature-renderer#5]
**Describe the bug**
The Nature Renderer component doesn't recognize the terrain. Note that this was working before and stopped working about a week ago. I have deleted the "Visual Design Cafe" directory and reimported the package multiple times without improving the situation.

**To Reproduce**
This happens 100% in my project with any terrain (even new ones). But I cannot reproduce it in a new project.

**Expected behavior**
I would expect to be able to add detail meshes to the Nature Renderer component. Instead I see the message "No terrain found".

**Screenshots**
This is what the issue looks like:
![image](https://github.com/visualdesigncafe/nature-renderer/assets/7487894/3811b991-9651-4f9d-afe8-d5933b42ce65)

The demo scene is also unable to be run. the loading bars in the game view just keep loading on a black background and I get warnings. The scene view does not show any vegetation:
![image](https://github.com/visualdesigncafe/nature-renderer/assets/7487894/d9d82d09-3cd5-4e19-a98b-889d8e5a6c51)

**Project:**
 - Unity version:2022.3.17f1
 - Render Pipeline: Universal Render Pipeline
 - Render Pipeline Version 14.0.9
 - Nature Renderer Version: 2022.0.2

**System:**
 - Platform: Microsoft Windows
 - Platform OS: Windows 10 22H2 (Build 19045.3930)
 - Graphics API and Version: DirectX11

**Comment by maxplooi** [comment]
Thank you for reporting this issue. This can potentially happen if the device or platform does not support procedural instancing, there is currently no specific error message for that scenario. I have added a warning message to the inspector for the next update.

To verify whether your device supports procedural instancing, can you add the following script to your project and then run **Tools > Print System Info** from the menu in the Unity editor?
```c#
using UnityEngine;
using VisualDesignCafe.Rendering.Nature;

public class PrintSystemInfo
{
    [UnityEditor.MenuItem( "Tools/Print System Info" )]
    public static void Print()
    {
        Debug.Log(
            "System supports procedural instancing: "
                + NatureRendererUtility.SystemSupportsProceduralInstancing() );
    }
}
``` 
If everything is supported then you will see a message printed in the console with "true", otherwise "false". If you believe your hardware should support procedural instancing then could you double check that the active platform for your project is one that is supported? (Generally, every platform except for WebGL, you can check the [list of supported platforms](https://visualdesigncafe.com/nature-renderer/docs/2022/compatibility#platforms))

**Comment by NoelWidmer** [comment]
Thank you for solving this mystery. I knew that WebGL is not supported since I also deploy to WebGL for playtest purposes. I read it in the docs and I experienced it myself while testing. But I wasn't aware that this limitation also applies to my Editor running on Windows while the selected platform is WebGL. 

This also explains while it suddenly stopped working.

The adjusted message will be useful fur future developers and would have helped me too. Thank you!
